Revert "Auto-remove duplicate expectations in UPF"
This reverts commit 8856db22ce4d8dac261cee3eb8ae9e988b6573e6.

Reason for revert: likely causing presubmit failures:
https://ci.chromium.org/ui/p/chromium/builders/ci/linux-presubmit/23402/infra
"""
ERROR: testSlowExpectationsDropped (__main__.CreateTestExpectationMapUnittest)
"""

Original change's description:
> Auto-remove duplicate expectations in UPF
>
> Updates the unexpected pass finder to automatically remove duplicate
> expectations from expectation files.
>
> Bug: 382526984
> Change-Id: I8432ffb74d3371e6ab1af408ffc2d2e6ef182b1d
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6160995
> Reviewed-by: Yuly Novikov <ynovikov@chromium.org>
> Auto-Submit: Brian Sheedy <bsheedy@chromium.org>
> Commit-Queue: Brian Sheedy <bsheedy@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1404450}

Bug: 382526984
Change-Id: Icc26592a2501b2aadf0518e2a6c28befc3425eab
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6166154
Commit-Queue: Ben Pastene <bpastene@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Ben Pastene <bpastene@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1404538}
NOKEYCHECK=True
GitOrigin-RevId: 66a1be987cf257b59805ed165a2b00fe84115cae