Revert "Roll WebView CTS Archive from akIIr4yAFQwo3j5WY... to dMHDxWyIpkzGNem_Z... (1 revision)"
This reverts commit c0b24c0d4eb9418644aad86c9faac355f8446234.

Reason for revert: Causing cts test failures:
https://ci.chromium.org/ui/p/chrome/builders/ci/webview-arm64-rel-ready

Message:
FileNotFoundError: [Errno 2] No such file or directory: '/b/swarming/w/ir/android_webview/tools/cts_archive/arm64/R/android-cts-arm64-11_r14.zip'

Original change's description:
> Roll WebView CTS Archive from akIIr4yAFQwo3j5WY... to dMHDxWyIpkzGNem_Z... (1 revision)
>
> If this roll has caused a breakage, revert this CL and stop the roller
> using the controls here:
> https://autoroll.skia.org/r/webview-cts-archive-chromium
> Please CC woa-engprod@google.com on the revert to ensure that a human
> is aware of the problem.
>
> To report a problem with the AutoRoller itself, please file a bug:
> https://issues.skia.org/issues/new?component=1389291&template=1850622
>
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md
>
> Cq-Include-Trybots: luci.chromium.try:android-webview-10-x86-rel-tests
> Bug: None
> Tbr: woa-engprod@google.com
> Change-Id: I8e23c6771ba88270d23e10eb5c43240b23061635
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5116063
> Reviewed-by: Nate Fischer <ntfschr@chromium.org>
> Commit-Queue: Mateusz Zbikowski <zbikowski@google.com>
> Reviewed-by: Haiyang Pan <hypan@google.com>
> Cr-Commit-Position: refs/heads/main@{#1236955}

Bug: None
Change-Id: I372c2f729642bdb53935ecd4b4616289aacc9b74
Cq-Include-Trybots: luci.chromium.try:android-webview-10-x86-rel-tests
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5120125
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Patrick Noland <pnoland@chromium.org>
Commit-Queue: Patrick Noland <pnoland@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1237017}
NOKEYCHECK=True
GitOrigin-RevId: 42da58962d36e7deb8dbd19635ef2567126da97c