Don't disable the field trial testing config with forced trials.
This fixes an issue where any browser test or interactive ui
test that was using a ScopedFeatureList with params would
disable the testing config entirely, due to the scoped override
state being converted to a --force-fieldtrials= command line
flag by BrowserTestBase::SetUp().

With the change, the flag will not preempt the testing config,
however any testing config entries that conflict with the
command-line will be skipped by the existing logic in
field_trial_util.cc's ShouldSkipExperiment().

Tests that were relying on running without the testing config
(i.e. failed with it) have been updated to explicitly pass
--disable-field-trial-config in separate CLs that have been
landed.
Exception: One PendingBeaconBackgroundTimeoutBrowserTest was
still failing which was not fixed up by a separate CL and is
being updated as part of this CL.

This CL also changes the bisect_variations.py script and the
command line produced by chrome://version/?show-variations-cmd
to specify --disable-field-trial-config as these are meant to
apply the state exactly as specified.

This CL will only land when trybots are green (once all dependent
CLs land).

Bug: 1491463
Change-Id: If2a2088881512fa703f70ce971a2fab5f58cc3bb
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4935093
Auto-Submit: Alexei Svitkine <asvitkine@chromium.org>
Commit-Queue: Alexei Svitkine <asvitkine@chromium.org>
Reviewed-by: Luc Nguyen <lucnguyen@google.com>
Reviewed-by: Ken Buchanan <kenrb@chromium.org>
Commit-Queue: Ken Buchanan <kenrb@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1212979}
NOKEYCHECK=True
GitOrigin-RevId: f89da71f560bcb29eaf8a58fe28336263d29357f