Revert "Add monochrome_apk_checker to kitkat waterfall."
This reverts commit fe87b3e051d3ac877193459d980ea9d6cdeb5220.

Reason for revert: Failing.

Example: https://ci.chromium.org/p/chromium/builders/ci/KitKat%20Phone%20Tester%20(dbg)/18869

Traceback (most recent call last):
  File "../../chrome/android/monochrome/scripts/monochrome_apk_checker.py", line 284, in <module>
    sys.exit(main())
  File "../../chrome/android/monochrome/scripts/monochrome_apk_checker.py", line 278, in main
    check_apk(chrome, chrome_pathmap)
  File "../../chrome/android/monochrome/scripts/monochrome_apk_checker.py", line 274, in check_apk
    VerifySameFile(monochrome_dict, chrome, CHROME_CHANGES)
  File "../../chrome/android/monochrome/scripts/monochrome_apk_checker.py", line 157, in VerifySameFile
    '\n'.join(diff))
Exception: The following files are not same as Monochrome:
 classes3.dex
classes4.dex
 

Original change's description:
> Add monochrome_apk_checker to kitkat waterfall.
> 
> The fact that it isn't running appears to have been an oversight.
> 
> Bug: 1029936
> Change-Id: I4c70311bca05f2088fd0e99112512a015524bd95
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1946875
> Commit-Queue: Erik Chen <erikchen@chromium.org>
> Commit-Queue: John Budorick <jbudorick@chromium.org>
> Auto-Submit: Erik Chen <erikchen@chromium.org>
> Reviewed-by: John Budorick <jbudorick@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#720719}

TBR=erikchen@chromium.org,jbudorick@chromium.org

Change-Id: Ib6fae3a9c2ef0c883a4fe086b2b6fb475341cfb2
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1029936
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1948486
Reviewed-by: danakj <danakj@chromium.org>
Commit-Queue: danakj <danakj@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#720994}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: bb621b6d76b1296f80b9ffa560b1abbab7e660da